default_config:

tts:
  - platform: google_translate
    service_name: google_say
    language: "pt"

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 2
  exclude:
    entities:
      - sun.sun

frontend:
  themes: !include_dir_merge_named themes

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

media_player:
  - platform: androidtv
    name: MiBox
    host: 192.168.1.45
  - platform: androidtv
    name: Firestick
    device_class: firetv
    host: 192.168.1.62
  - platform: lg_netcast
    name: TV do Quarto
    host: 192.168.1.47
    access_token: !secret tv_quarto_access_token

binary_sensor:
  - platform: template
    sensors:
      dirigindo:
        friendly_name: "Dirigindo"
        # yamllint disable rule:line-length
        value_template: "{{'90:3A:E6:18:2F:F8' in state_attr('sensor.s20_bluetooth_connection', 'connected_paired_devices') }}"
        # yamllint enable rule:line-length

sensor:
  - platform: command_line
    name: Temperatura CPU
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: "{{ value | multiply(0.001)|round(1) }}"
    scan_interval: 5

template:
  - sensor:
      - name: Consumo da Casa
        unit_of_measurement: W
        # yamllint disable rule:line-length
        state: "{{ (states.sensor.potencia_geral.state|float)-(states.sensor.consumo_da_geladeira.state|float)}}"
        # yamllint enable rule:line-length

input_number:
  ar_meninos_timer_minutes:
    name: "Ar Condicionado dos Meninos - Timer"
    min: 0
    max: 180
    step: 1

input_boolean:
  ar_meninos_timer_enabled:
    name: "Ar Condicionado dos Meninos - Timer"
    initial: off
    icon: mdi:timelapse

timer:
  ar_meninos_timer:
    name: Ar Condicionado dos Meninos - Timer

google_assistant:
  project_id: !secret google_assistant_project_id
  report_state: true
  service_account:
    private_key: !secret google_assistant_private_key
    client_email: !secret google_assistant_client_email

utility_meter:
  daily_energy:
    source: sensor.consumo_total
    cycle: daily
  weekly_energy:
    source: sensor.consumo_total
    cycle: weekly
  monthly_energy:
    source: sensor.consumo_total
    cycle: monthly
  geladeira_daily:
    source: sensor.consumo_diario_geladeira
    cycle: daily
  geladeira_monthly:
    source: sensor.consumo_diario_geladeira
    cycle: monthly

weback:
  username: !secret weback_username
  password: !secret weback_password

alarm_control_panel:
  - platform: manual
    name: Alarme
    delay_time: 0
    arming_time: 0
    trigger_time: 60000

alexa:
  smart_home:
    filter:
      include_entities:
        - switch.bomba
      include_entity_globs:
        - binary_sensor.porta*
        - binary_sensor.movimento_*
      include_domains:
        - light
        - fan
        - climate
        - vacuum
      exclude_domains:
        - switch
    entity_config:
      vacuum.hx_x506_cc_50_e3_59_15_b1:
        name: "C3 do Pó"

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id

notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_bot_chat_id
