wifi_ssid: "asdfghjkl"
wifi_password: "asdfghjkl"
api_password: "asdfghjkl"
api_key: "RI6N+4hINGcnEgEZTilf2tPadG/uqqbdK+XzVu9mDl0="
ota_password: "asdfghjkl"
rf_portao_garagem_1: "123"
rf_portao_garagem_2: "123"
rf_portao_garagem_3: "123"
rf_movimento_escada_baixo: "123"
rf_movimento_escada_cima: "123"
rf_movimento_garagem: "123"
rf_porta_frente_abrir: "123"
rf_porta_frente_fechar: "123"
rf_porta_tras_abrir: "123"
rf_porta_tras_fechar: "123"
