esphome:
  name: ar_condicionado_meninos
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.122

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

sensor:
  - platform: dht
    pin: D6

    temperature:
      id: temp
      name: Temperatura do Quarto dos Meninos
    humidity:
      name: Umidade do Quarto dos Meninos
    model: DHT22
    update_interval: 2s

light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: D1
    num_leds: 117
    rgb_order: BRG
    id: led
    name: "Luminaria dos meninos"
    effects:
      - random:
      - strobe:
      - addressable_rainbow:
      - addressable_fireworks:

remote_receiver:
  pin:
    number: D7
    mode: INPUT_PULLUP
    inverted: true
  dump: nec
  id: ir_rcv
  tolerance: 60

remote_transmitter:
  pin:
    number: D2
    inverted: true
  carrier_duty_percent: 100%
  id: ir_tra

climate:
  - platform: coolix
    id: ar_condicionado
    sensor: temp
    receiver_id: ir_rcv
    transmitter_id: ir_tra
    name: "Ar Condicionado dos Meninos"
    supports_heat: false
    visual:
      temperature_step: 1
      min_temperature: 17
      max_temperature: 30

binary_sensor:
  - platform: remote_receiver
    id: "on"
    nec:
      address: 0x00FF
      command: 0xF20D
    on_press:
      - if:
          condition:
            lambda: 'return (id(ar_condicionado).mode==CLIMATE_MODE_OFF);'
          then:
            - climate.control:
                id: ar_condicionado
                mode: COOL
                target_temperature: 25°C
          else:
            - climate.control:
                id: ar_condicionado
                mode: 'OFF'
  - platform: remote_receiver
    id: "off"
    nec:
      address: 0x00FF
      command: 0xE01F
    on_press:
      - homeassistant.service:
          service: homeassistant.toggle
          data: {"entity_id": "light.luz_do_quarto_dos_meninos"}
  - platform: remote_receiver
    id: brightness_up
    nec:
      address: 0x00FF
      command: 0xF609
    on_press:
      then:
        - light.dim_relative:
            id: led
            relative_brightness: 20%
  - platform: remote_receiver
    id: brightness_down
    nec:
      address: 0x00FF
      command: 0xE21D
    on_press:
      then:
        - light.dim_relative:
            id: led
            relative_brightness: -20%
  - platform: remote_receiver
    id: red
    nec:
      address: 0x00FF
      command: 0x9867
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 100%
            green: 0
            blue: 0
  - platform: remote_receiver
    id: green
    nec:
      address: 0x00FF
      command: 0xD827
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 0
            green: 100%
            blue: 0
  - platform: remote_receiver
    id: blue
    nec:
      address: 0x00FF
      command: 0x8877
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 0
            green: 0
            blue: 100%
  - platform: remote_receiver
    id: white
    nec:
      address: 0x00FF
      command: 0xA857
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 100%
            green: 100%
            blue: 100%
  - platform: remote_receiver
    id: R2
    nec:
      address: 0x00FF
      command: 0xE817
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 100%
            green: 35%
            blue: 14%
  - platform: remote_receiver
    id: R3
    nec:
      address: 0x00FF
      command: 0x02FD
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 100%
            green: 57%
            blue: 14%
  - platform: remote_receiver
    id: R4
    nec:
      address: 0x00FF
      command: 0x50AF
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 100%
            green: 78%
            blue: 28%
  - platform: remote_receiver
    id: R5
    nec:
      address: 0x00FF
      command: 0x38C7
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 100%
            green: 100%
            blue: 0%
  #Greens
  - platform: remote_receiver
    id: G2
    nec:
      address: 0x00FF
      command: 0x48B7
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 28%
            green: 100%
            blue: 28%
  - platform: remote_receiver
    id: G3
    nec:
      address: 0x00FF
      command: 0x32CD
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 28%
            green: 100%
            blue: 64%
  - platform: remote_receiver
    id: G4
    nec:
      address: 0x00FF
      command: 0x7887
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 28%
            green: 64%
            blue: 100%
  - platform: remote_receiver
    id: G5
    nec:
      address: 0x00FF
      command: 0x28D7
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 14%
            green: 35%
            blue: 100%
  #Blues
  - platform: remote_receiver
    id: B2
    nec:
      address: 0x00FF
      command: 0x6897
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 14%
            green: 14%
            blue: 100%
  - platform: remote_receiver
    id: B3
    nec:
      address: 0x00FF
      command: 0x20DF
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 46%
            green: 28%
            blue: 100%
  - platform: remote_receiver
    id: B4
    nec:
      address: 0x00FF
      command: 0x708F
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 81%
            green: 28%
            blue: 100%
  - platform: remote_receiver
    id: B5
    nec:
      address: 0x00FF
      command: 0xF00F
    on_press:
      then:
        - light.turn_on:
            id: led
            red: 100%
            green: 14%
            blue: 78%
