esphome:
  name: ar_condicionado_quarto
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.170

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

sensor:
  - platform: dht
    pin: D1
    temperature:
      id: temp
      name: Temperatura do Quarto
    humidity:
      name: Umidade do Quarto
    model: DHT22
    update_interval: 2s

remote_receiver:
  pin:
    number: D7
    mode: INPUT_PULLUP
    inverted: true
  dump: nec
  id: ir_rcv
  tolerance: 60

remote_transmitter:
  pin:
    number: D2
    inverted: true
  carrier_duty_percent: 100%
  id: ir_tra

climate:
  - platform: coolix
    id: ar_condicionado
    sensor: temp
    receiver_id: ir_rcv
    transmitter_id: ir_tra
    name: "Ar Condicionado do Quarto"
    supports_heat: false
    visual:
      temperature_step: 1
      min_temperature: 17
      max_temperature: 30

binary_sensor:
  - platform: remote_receiver
    id: "on"
    nec:
      address: 0xFB04
      command: 0x9E61
    on_press:
      - if:
          condition:
            lambda: 'return (id(ar_condicionado).mode==CLIMATE_MODE_OFF);'
          then:
            - climate.control:
                id: ar_condicionado
                mode: COOL
                target_temperature: 25°C
          else:
            - climate.control:
                id: ar_condicionado
                mode: 'OFF'
