esphome:
  name: bomba
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.224

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

sensor:
  - platform: ultrasonic
    timeout: 1m
    trigger_pin: GPIO2
    echo_pin: RX
    update_interval: 1s
    name: "Nivel da Cisterna"
    unit_of_measurement: "%"
    icon: "mdi:water"
    accuracy_decimals: 1
    filters:
      - median:
      - lambda: return 100-((x*100-21)/((64−21)/100));
      - delta: 0.3

binary_sensor:
  - platform: gpio
    id: btn
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: Bomba
    pin: GPIO12
    id: relay
    on_turn_on:
      - delay:
          minutes: 20
      - switch.turn_off: relay
