esphome:
  name: infrared
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

# GPIO	Component	Description
# 04	LED1i (52)	Blue LED - Link status
# 05	IRrecv (51)	IR Receiver
# 13	Button1 (17)	Button
# 14	IRsend (8)	IR Transmitter

remote_transmitter:
  id: ir_tra
  pin: GPIO14
  carrier_duty_percent: 50%

remote_receiver:
  id: rcvr
  pin:
    number: GPIO5
    inverted: True
  tolerance: 55%
  dump: nec

climate:
  - platform: coolix
    name: "AC Quarto"
    transmitter_id: ir_tra
    supports_heat: false
    visual:
      temperature_step: 1
      min_temperature: 20
      max_temperature: 30

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Infrared Button"
    on_press:
      - logger.log: "Infrared button"
      - light.turn_on: light_led
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xF708
      - delay: 1s
      - light.turn_off: light_led

button:
  - platform: template
    name: Ligar/Desligar
    id: btn_ligar
    icon: "mdi:power"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xF708
  - platform: template
    name: Aumentar Volume
    id: btn_vol_up
    icon: "mdi:volume-plus"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xFD02
  - platform: template
    name: Diminuir Volume
    id: btn_vol_down
    icon: "mdi:volume-minus"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xFC03
  - platform: template
    name: Aumentar Canal
    id: btn_ch_up
    icon: "mdi:arrow-up-bold"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xFF00
  - platform: template
    name: Diminuir Canal
    id: btn_ch_down
    icon: "mdi:arrow-down-bold"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xFE01
  - platform: template
    name: Globo
    id: btn_macro_globo
    icon: "mdi:television-classic"
    on_press:
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xEE11
      - delay: 500ms
      - remote_transmitter.transmit_nec:
          address: 0xFB04
          command: 0xEF10

output:
  - platform: esp8266_pwm
    id: esphome_ir1_led
    pin:
      number: GPIO4
      inverted: false

light:
  - platform: monochromatic
    name: "Blue LED"
    output: esphome_ir1_led
    id: light_led