esphome:
  name: luz-sala

esp8266:
  board: d1_mini

# Dica: Para múltiplos dispositivos, considere usar a função "packages" do ESPHome
# para centralizar configurações comuns como wifi, api, ota, etc. em um arquivo separado.
# https://esphome.io/components/packages.html

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

api:
  reboot_timeout: 0s
  encryption:
    key: !secret api_key

logger:

ota:
  - platform: esphome
    password: !secret api_password

time:
  platform: homeassistant
  id: ha_time

external_components:
  - source: "./custom_components"
    components: [rf433]

rf433:
  pin: D2
  readed_value:
    id: rf_code_sensor
    on_value:
      then:
        # Lógica para os sensores de movimento da escada
        - if:
            condition:
              text_sensor.state:
                id: rf_code_sensor
                state: !secret rf_movimento_escada_baixo # Movimento Escada Baixo
            then:
              - binary_sensor.template.publish:
                  id: movimento_escada_baixo
                  state: ON
              - script.execute: trigger_luz_escada
        - if:
            condition:
              text_sensor.state:
                id: rf_code_sensor
                state: !secret rf_movimento_escada_cima # Movimento Escada Cima
            then:
              - binary_sensor.template.publish:
                  id: movimento_escada_cima
                  state: ON
              - script.execute: trigger_luz_escada

        # Lógica para o sensor de movimento da garagem
        - if:
            condition:
              text_sensor.state:
                id: rf_code_sensor
                state: !secret rf_movimento_garagem
            then:
              - binary_sensor.template.publish:
                  id: movimento_garagem
                  state: ON

        # Lógica para o sensor da porta da frente
        - if:
            condition:
              text_sensor.state:
                id: rf_code_sensor
                state: !secret rf_porta_frente_abrir # Abrir
            then:
              - binary_sensor.template.publish:
                  id: porta_frente
                  state: ON
        - if:
            condition:
              text_sensor.state:
                id: rf_code_sensor
                state: !secret rf_porta_frente_fechar # Fechar
            then:
              - binary_sensor.template.publish:
                  id: porta_frente
                  state: OFF

        # Lógica para o sensor da porta de trás
        - if:
            condition:
              text_sensor.state:
                id: rf_code_sensor
                state: !secret rf_porta_tras_abrir # Abrir
            then:
              - binary_sensor.template.publish:
                  id: porta_tras
                  state: ON
        - if:
            condition:
              text_sensor.state:
                id: rf_code_sensor
                state: !secret rf_porta_tras_fechar # Fechar
            then:
              - binary_sensor.template.publish:
                  id: porta_tras
                  state: OFF

script:
  - id: turn_off_luz_escada_timer
    mode: restart
    then:
      - delay: 30s
      - homeassistant.service:
          service: light.turn_off
          data:
            entity_id: light.luz_escada_1

  - id: trigger_luz_escada
    mode: single
    then:
      - if:
          condition:
            lambda: "return id(sun_elevation).state < 0.0;"
          then:
            - homeassistant.service:
                service: light.turn_on
                data:
                  entity_id: light.luz_escada_1
            - script.execute: turn_off_luz_escada_timer

sensor:
  - platform: homeassistant
    id: sun_elevation
    entity_id: sun.sun
    attribute: elevation

binary_sensor:
  - platform: gpio
    id: swt1
    pin:
      number: D1
      mode: INPUT_PULLUP
    on_state:
      - light.toggle: light1
  - platform: gpio
    id: swt2
    pin:
      number: D7
      mode: INPUT_PULLUP
    on_state:
      - light.toggle: light2
  - platform: gpio
    id: swt3
    pin:
      number: D5
      mode: INPUT_PULLUP
    on_state:
      - homeassistant.service:
          service: homeassistant.toggle
          data: { "entity_id": "light.luz_escada_1" }

  - platform: template
    name: "Porta da Frente"
    id: porta_frente
    device_class: door

  - platform: template
    name: "Porta de Tras"
    id: porta_tras
    device_class: door

  # Os sensores de movimento agora desligam automaticamente após 1s,
  # simplificando as automações.
  - platform: template
    name: "Movimento Escada Baixo"
    id: movimento_escada_baixo
    device_class: motion

  - platform: template
    name: "Movimento Escada Cima"
    id: movimento_escada_cima
    device_class: motion

  - platform: template
    name: "Movimento Garagem"
    id: movimento_garagem
    device_class: motion

output:
  - platform: gpio
    id: relay1
    pin: D6
  - platform: gpio
    id: relay2
    pin: D8

light:
  - platform: binary
    id: light1
    name: Luz da Sala
    output: relay1
  - platform: binary
    id: light2
    name: Luz da Garagem
    output: relay2

status_led:
  pin:
    number: D4
    inverted: true
