esphome:
  name: luz_varanda
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.229

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

binary_sensor:
  - platform: gpio
    id: btn
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: luz
  - platform: gpio
    id: swt
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
      - delayed_off: 500ms
    on_state:
      - light.toggle: luz

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: luz
    name: Luz da Varanda
    output: relay

status_led:
  pin:
    number: GPIO13
    inverted: true
