esphome:
  name: luz_aquario
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.119

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

switch:
  - platform: gpio
    name: Bomba Aquario
    restore_mode: ALWAYS_ON
    pin: GPIO12
    id: relay

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO2
    num_leds: 20
    rgb_order: GRB
    id: led
    name: "Luz do aquario"
    max_refresh_rate: 32ms
    effects:
      - random:
      - strobe:
      - flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
      - addressable_fireworks:
      - addressable_flicker:

binary_sensor:
  - platform: gpio
    id: btn
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: led

  - platform: remote_receiver
    id: PortaFrenteFechada
    rc_switch_raw:
      code: '010010111000011100001110'
      protocol:
        pulse_length: 454
    internal: true
    on_press:
      - homeassistant.service:
          service: switch.turn_off
          data: {"entity_id": "switch.porta_da_frente"}

  - platform: remote_receiver
    id: PortaFrenteAberta
    rc_switch_raw:
      code: '010010111000011100001010'
      protocol:
        pulse_length: 454
    internal: true
    on_press:
      - homeassistant.service:
          service: switch.turn_on
          data: {"entity_id": "switch.porta_da_frente"}

  - platform: remote_receiver
    id: PortaTrasFechada
    rc_switch_raw:
      code: '001111001011100100001110'
    internal: true
    on_press:
      - homeassistant.service:
          service: switch.turn_off
          data: {"entity_id": "switch.porta_de_tras"}
  - platform: remote_receiver
    id: PortaTrasAberta
    rc_switch_raw:
      code: '001111001011100100001010'
    internal: true
    on_press:
      - homeassistant.service:
          service: switch.turn_on
          data: {"entity_id": "switch.porta_de_tras"}
  - platform: remote_receiver
    id: LigarAlarme
    rc_switch_raw:
      code: '111111110101111101111000'
    internal: true
    on_press:
      - homeassistant.service:
          service: alarm_control_panel.alarm_arm_away
          data: {"entity_id": "alarm_control_panel.home_alarm", "code": "2117"}
  - platform: remote_receiver
    id: DesligarAlarme
    rc_switch_raw:
      code: '111111110101111101110010'
    internal: true
    on_press:
      - homeassistant.service:
          service: alarm_control_panel.alarm_disarm
          data: {"entity_id": "alarm_control_panel.home_alarm", "code": "2117"}
  - platform: remote_receiver
    name: Movimento Escada Cima
    internal: true
    device_class: motion
    rc_switch_raw:
      code: '111111000111100000011110'
    on_press:
      - homeassistant.service:
          service: switch.turn_on
          data: {"entity_id": "binary_sensor.movimento_escada_cima"}
    on_release:
      - homeassistant.service:
          service: switch.turn_off
          data: {"entity_id": "binary_sensor.movimento_escada_cima"}

remote_receiver:
  pin:
    number: TX
    mode: INPUT_PULLUP
  dump: rc_switch
  tolerance: 60%
  filter: 350us
  buffer_size: 2kb
