esphome:
  name: luz_quintal
  platform: ESP8266
  board: d1_mini #esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.233

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

binary_sensor:
  - platform: gpio
    id: swt1
    pin:
      number: 5
      mode: INPUT_PULLUP
    on_state:
      - light.toggle: light1
  - platform: gpio
    id: swt2
    pin:
      number: 14
      mode: INPUT_PULLUP
    on_state:
      - light.toggle: light2

output:
  - platform: gpio
    id: relay1
    pin: 12
  - platform: gpio
    id: relay2
    pin: 4

light:
  - platform: binary
    id: light1
    name: Luz da Area de Servico
    output: relay1
  - platform: binary
    id: light2
    name: Luz do Quintal
    output: relay2

status_led:
  pin:
    number: 2
    inverted: true
