esphome:
  name: luz_banheiro_teto
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.120

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password


binary_sensor:
  - platform: gpio
    id: btn
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: luz
  - platform: gpio
    id: swt
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
    filters:
      - delayed_on_off: 50ms
    on_state:
      then:
        - light.toggle: luz
        - if:
            condition:
              light.is_on: luz
            then:
              - homeassistant.service:
                  service: homeassistant.turn_on
                  data: {"entity_id": "light.luz_do_espelho_do_banheiro"}
        - if:
            condition:
              light.is_off: luz
            then:
              - homeassistant.service:
                  service: homeassistant.turn_off
                  data: {"entity_id": "light.luz_do_espelho_do_banheiro"}


output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: luz
    name: Luz do Teto do Banheiro
    output: relay

status_led:
  pin:
    number: GPIO13
    inverted: true
