esphome:
  name: medidor_geladeira
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.212

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

sensor:
  - platform: total_daily_energy
    name: "Consumo Diario Geladeira"
    power_id: my_power
    filters:
      - multiply: 0.001
    accuracy_decimals: 3
    unit_of_measurement: kWh
    device_class: energy
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    change_mode_every: 3
    update_interval: 3s
    current:
      name: "Corrente da Geladeira"
      filters:
        - multiply: 1.26
    voltage:
      name: "Voltagem da Geladeira"
      filters:
        - multiply: 1.15
    power:
      name: "Consumo da Geladeira"
      id: my_power
      filters:
        - multiply: 1.36

time:
  - platform: homeassistant
    id: my_time
    timezone: 'America/Fortaleza'

status_led:
  pin:
    number: 15
    inverted: false

switch:
  - platform: gpio
    name: "Geladeira"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

binary_sensor:
  - platform: gpio
    id: btn
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay
