esphome:
  name: medidor-cima

esp32:
  board: esp32dev
  framework:
    type: arduino


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.221

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    name: "Current"
    update_interval: 1s
    filters:
      - calibrate_linear:
        - 0.061 -> 0
        - 0.08 -> 0.4
  - platform: adc
    pin: 35
    attenuation: 11db
    id: adc_sensor