esphome:
  name: ventilador_meninos
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  use_address: 192.168.2.163

api:
  password: !secret api_password

logger:

ota:
  password: !secret api_password

fan:
  - platform: binary
    id: vent
    name: "Ventilador dos Meninos"
    output: relay

output:
  - platform: gpio
    pin: GPIO12
    id: relay

binary_sensor:
  - platform: gpio
    id: btn
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - fan.toggle: vent
